global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metrics-service'
    static_configs:
      - targets: ['host.docker.internal:3007']

  - job_name: 'authentication-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'bdd-service'
    static_configs:
      - targets: ['host.docker.internal:3004']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:3006']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:3002']

  - job_name: 'ia-service'
    static_configs:
      - targets: ['host.docker.internal:3005']

  - job_name: 'frontend'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3000'] 